"""create form block table

Revision ID: 07eb29fdd4da
Revises: dacd650c930e
Create Date: 2025-09-15 02:24:17.667370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07eb29fdd4da'
down_revision: Union[str, Sequence[str], None] = 'dacd650c930e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('TEXT', 'LONG_TEXT', 'SINGLE_CHOICE', 'MULTICHOICE', 'CHECKBOX', 'DATE', 'NUMBER', name='block_type_enum', schema='form'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.forms.id'], name='fk_form_blocks_form_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'order', name='uq_form_blocks_form_order'),
    schema='form'
    )
    op.create_index('ix_form_blocks_form_id', 'form_blocks', ['form_id'], unique=False, schema='form')
    op.create_index('ix_form_blocks_form_id_order', 'form_blocks', ['form_id', 'order'], unique=False, schema='form')
    op.create_index('ix_form_blocks_type', 'form_blocks', ['type'], unique=False, schema='form')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_form_blocks_type', table_name='form_blocks', schema='form')
    op.drop_index('ix_form_blocks_form_id_order', table_name='form_blocks', schema='form')
    op.drop_index('ix_form_blocks_form_id', table_name='form_blocks', schema='form')
    op.drop_table('form_blocks', schema='form')
    # ### end Alembic commands ###
