"""add form_analytics and block_analytics tables

Revision ID: 536888a35ac8
Revises: 18cb69564741
Create Date: 2025-10-07 16:42:16.252755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '536888a35ac8'
down_revision: Union[str, Sequence[str], None] = '18cb69564741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics;")
    op.create_table('form_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', name='uq_form_analytics_form_id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_form_analytics_form_id'), 'form_analytics', ['form_id'], unique=False, schema='analytics')
    op.create_index('ix_form_analytics_details', 'form_analytics', ['details'], unique=False, schema='analytics', postgresql_using='gin')
    op.create_table('block_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['form.form_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['form.forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', name='uq_block_analytics_block_id'),
    schema='analytics'
    )
    op.create_index('ix_block_analytics_details', 'block_analytics', ['details'], unique=False, schema='analytics', postgresql_using='gin')
    op.create_index('ix_block_analytics_form_id', 'block_analytics', ['form_id'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_analytics_form_id', table_name='block_analytics', schema='analytics')
    op.drop_index('ix_block_analytics_details', table_name='block_analytics', schema='analytics', postgresql_using='gin')
    op.drop_table('block_analytics', schema='analytics')
    op.drop_index('ix_form_analytics_details', table_name='form_analytics', schema='analytics', postgresql_using='gin')
    op.drop_index(op.f('ix_analytics_form_analytics_form_id'), table_name='form_analytics', schema='analytics')
    op.drop_table('form_analytics', schema='analytics')
    # ### end Alembic commands ###
