"""init form schema and forms table

Revision ID: dacd650c930e
Revises: 
Create Date: 2025-09-15 01:38:12.214184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacd650c930e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE SCHEMA IF NOT EXISTS "form";')

    op.create_table(
        "forms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(200), nullable=False),
        sa.Column("status", sa.Enum("DRAFT","PUBLISHED", name="status_enum", schema="form"), nullable=False),
        sa.Column("access", sa.Enum("PUBLIC","LOGIN_REQUIRED", name="access_enum", schema="form"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_forms_slug"),
        schema="form",
    )
    op.create_index("ix_forms_status", "forms", ["status"], schema="form")
    op.create_index("ix_forms_access", "forms", ["access"], schema="form")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_forms_status", table_name="forms", schema="form")
    op.drop_index("ix_forms_access", table_name="forms", schema="form")
    op.drop_table("forms", schema="form")

    bind = op.get_bind()
    sa.Enum(name="status_enum", schema="form").drop(bind, checkfirst=True)
    sa.Enum(name="access_enum", schema="form").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
